"use client";

// import type { Metadata } from "next";
import { Noto_Sans_JP } from 'next/font/google'

const noto_sans_jp = Noto_Sans_JP({
  subsets: ['latin'],
  weight: ['400','700']
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <head>
        <title>AZUMA GORGE SAUNA</title>
        <meta name="description" content="AZUMA GORGE SAUNA はテントサウナレンタルサービスを行っています"/>
      </head>
      <body className={noto_sans_jp.className}>{children}</body>
    </html>
  );
}
